version: '3.7'

services:
  test-app:
    image: zmex/spring-in-docker
    container_name: spring-in-docker
    ports:
      - 8080:8080
    restart: always
    links:
      - postgres

  postgres:
    image: postgres
    container_name: heals_database
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
      restart: always
